# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/timber30/Documents/research/mpo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/timber30/Documents/research/mpo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timber30/Documents/research/mpo/CMakeFiles /home/timber30/Documents/research/mpo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/timber30/Documents/research/mpo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named INIH_MAKE

# Build rule for target.
INIH_MAKE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 INIH_MAKE
.PHONY : INIH_MAKE

# fast build rule for target.
INIH_MAKE/fast:
	$(MAKE) -f CMakeFiles/INIH_MAKE.dir/build.make CMakeFiles/INIH_MAKE.dir/build
.PHONY : INIH_MAKE/fast

#=============================================================================
# Target rules for targets named config_test

# Build rule for target.
config_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 config_test
.PHONY : config_test

# fast build rule for target.
config_test/fast:
	$(MAKE) -f CMakeFiles/config_test.dir/build.make CMakeFiles/config_test.dir/build
.PHONY : config_test/fast

#=============================================================================
# Target rules for targets named doc_doxygen

# Build rule for target.
doc_doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_doxygen
.PHONY : doc_doxygen

# fast build rule for target.
doc_doxygen/fast:
	$(MAKE) -f CMakeFiles/doc_doxygen.dir/build.make CMakeFiles/doc_doxygen.dir/build
.PHONY : doc_doxygen/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f bayesopt/CMakeFiles/doc.dir/build.make bayesopt/CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named doxygen

# Build rule for target.
doxygen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doxygen
.PHONY : doxygen

# fast build rule for target.
doxygen/fast:
	$(MAKE) -f bayesopt/CMakeFiles/doxygen.dir/build.make bayesopt/CMakeFiles/doxygen.dir/build
.PHONY : doxygen/fast

#=============================================================================
# Target rules for targets named bayesopt

# Build rule for target.
bayesopt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bayesopt
.PHONY : bayesopt

# fast build rule for target.
bayesopt/fast:
	$(MAKE) -f bayesopt/CMakeFiles/bayesopt.dir/build.make bayesopt/CMakeFiles/bayesopt.dir/build
.PHONY : bayesopt/fast

#=============================================================================
# Target rules for targets named nlopt

# Build rule for target.
nlopt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nlopt
.PHONY : nlopt

# fast build rule for target.
nlopt/fast:
	$(MAKE) -f bayesopt/nlopt2/CMakeFiles/nlopt.dir/build.make bayesopt/nlopt2/CMakeFiles/nlopt.dir/build
.PHONY : nlopt/fast

#=============================================================================
# Target rules for targets named bo_oned

# Build rule for target.
bo_oned: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bo_oned
.PHONY : bo_oned

# fast build rule for target.
bo_oned/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/bo_oned.dir/build.make bayesopt/examples/CMakeFiles/bo_oned.dir/build
.PHONY : bo_oned/fast

#=============================================================================
# Target rules for targets named bo_cont

# Build rule for target.
bo_cont: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bo_cont
.PHONY : bo_cont

# fast build rule for target.
bo_cont/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/bo_cont.dir/build.make bayesopt/examples/CMakeFiles/bo_cont.dir/build
.PHONY : bo_cont/fast

#=============================================================================
# Target rules for targets named branin_system_calls

# Build rule for target.
branin_system_calls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 branin_system_calls
.PHONY : branin_system_calls

# fast build rule for target.
branin_system_calls/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/branin_system_calls.dir/build.make bayesopt/examples/CMakeFiles/branin_system_calls.dir/build
.PHONY : branin_system_calls/fast

#=============================================================================
# Target rules for targets named bo_branin

# Build rule for target.
bo_branin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bo_branin
.PHONY : bo_branin

# fast build rule for target.
bo_branin/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/bo_branin.dir/build.make bayesopt/examples/CMakeFiles/bo_branin.dir/build
.PHONY : bo_branin/fast

#=============================================================================
# Target rules for targets named bo_display

# Build rule for target.
bo_display: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bo_display
.PHONY : bo_display

# fast build rule for target.
bo_display/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/bo_display.dir/build.make bayesopt/examples/CMakeFiles/bo_display.dir/build
.PHONY : bo_display/fast

#=============================================================================
# Target rules for targets named bo_disc

# Build rule for target.
bo_disc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bo_disc
.PHONY : bo_disc

# fast build rule for target.
bo_disc/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/bo_disc.dir/build.make bayesopt/examples/CMakeFiles/bo_disc.dir/build
.PHONY : bo_disc/fast

#=============================================================================
# Target rules for targets named bo_branin_display

# Build rule for target.
bo_branin_display: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bo_branin_display
.PHONY : bo_branin_display

# fast build rule for target.
bo_branin_display/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/bo_branin_display.dir/build.make bayesopt/examples/CMakeFiles/bo_branin_display.dir/build
.PHONY : bo_branin_display/fast

#=============================================================================
# Target rules for targets named bo_branin_mcmc

# Build rule for target.
bo_branin_mcmc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bo_branin_mcmc
.PHONY : bo_branin_mcmc

# fast build rule for target.
bo_branin_mcmc/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/bo_branin_mcmc.dir/build.make bayesopt/examples/CMakeFiles/bo_branin_mcmc.dir/build
.PHONY : bo_branin_mcmc/fast

#=============================================================================
# Target rules for targets named branin_xml

# Build rule for target.
branin_xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 branin_xml
.PHONY : branin_xml

# fast build rule for target.
branin_xml/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/branin_xml.dir/build.make bayesopt/examples/CMakeFiles/branin_xml.dir/build
.PHONY : branin_xml/fast

#=============================================================================
# Target rules for targets named bo_branin_timed

# Build rule for target.
bo_branin_timed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bo_branin_timed
.PHONY : bo_branin_timed

# fast build rule for target.
bo_branin_timed/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/bo_branin_timed.dir/build.make bayesopt/examples/CMakeFiles/bo_branin_timed.dir/build
.PHONY : bo_branin_timed/fast

#=============================================================================
# Target rules for targets named bo_compare

# Build rule for target.
bo_compare: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bo_compare
.PHONY : bo_compare

# fast build rule for target.
bo_compare/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/bo_compare.dir/build.make bayesopt/examples/CMakeFiles/bo_compare.dir/build
.PHONY : bo_compare/fast

#=============================================================================
# Target rules for targets named bo_hartmann

# Build rule for target.
bo_hartmann: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bo_hartmann
.PHONY : bo_hartmann

# fast build rule for target.
bo_hartmann/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/bo_hartmann.dir/build.make bayesopt/examples/CMakeFiles/bo_hartmann.dir/build
.PHONY : bo_hartmann/fast

#=============================================================================
# Target rules for targets named matplotpp

# Build rule for target.
matplotpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 matplotpp
.PHONY : matplotpp

# fast build rule for target.
matplotpp/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/matplotpp.dir/build.make bayesopt/examples/CMakeFiles/matplotpp.dir/build
.PHONY : matplotpp/fast

#=============================================================================
# Target rules for targets named bo_camelback

# Build rule for target.
bo_camelback: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bo_camelback
.PHONY : bo_camelback

# fast build rule for target.
bo_camelback/fast:
	$(MAKE) -f bayesopt/examples/CMakeFiles/bo_camelback.dir/build.make bayesopt/examples/CMakeFiles/bo_camelback.dir/build
.PHONY : bo_camelback/fast

#=============================================================================
# Target rules for targets named DesignEasy

# Build rule for target.
DesignEasy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DesignEasy
.PHONY : DesignEasy

# fast build rule for target.
DesignEasy/fast:
	$(MAKE) -f DesignEasy/DesignEasy/SourceCode/CMakeFiles/DesignEasy.dir/build.make DesignEasy/DesignEasy/SourceCode/CMakeFiles/DesignEasy.dir/build
.PHONY : DesignEasy/fast

#=============================================================================
# Target rules for targets named de_interface

# Build rule for target.
de_interface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 de_interface
.PHONY : de_interface

# fast build rule for target.
de_interface/fast:
	$(MAKE) -f DesignEasy/DesignEasy/SourceCode/CMakeFiles/de_interface.dir/build.make DesignEasy/DesignEasy/SourceCode/CMakeFiles/de_interface.dir/build
.PHONY : de_interface/fast

src/benchmark.o: src/benchmark.cpp.o

.PHONY : src/benchmark.o

# target to build an object file
src/benchmark.cpp.o:
	$(MAKE) -f CMakeFiles/config_test.dir/build.make CMakeFiles/config_test.dir/src/benchmark.cpp.o
.PHONY : src/benchmark.cpp.o

src/benchmark.i: src/benchmark.cpp.i

.PHONY : src/benchmark.i

# target to preprocess a source file
src/benchmark.cpp.i:
	$(MAKE) -f CMakeFiles/config_test.dir/build.make CMakeFiles/config_test.dir/src/benchmark.cpp.i
.PHONY : src/benchmark.cpp.i

src/benchmark.s: src/benchmark.cpp.s

.PHONY : src/benchmark.s

# target to generate assembly for a file
src/benchmark.cpp.s:
	$(MAKE) -f CMakeFiles/config_test.dir/build.make CMakeFiles/config_test.dir/src/benchmark.cpp.s
.PHONY : src/benchmark.cpp.s

src/config.o: src/config.cpp.o

.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) -f CMakeFiles/config_test.dir/build.make CMakeFiles/config_test.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i

.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) -f CMakeFiles/config_test.dir/build.make CMakeFiles/config_test.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s

.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) -f CMakeFiles/config_test.dir/build.make CMakeFiles/config_test.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/config_test.dir/build.make CMakeFiles/config_test.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/config_test.dir/build.make CMakeFiles/config_test.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/config_test.dir/build.make CMakeFiles/config_test.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... INIH_MAKE"
	@echo "... config_test"
	@echo "... doc_doxygen"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... doc"
	@echo "... doxygen"
	@echo "... bayesopt"
	@echo "... nlopt"
	@echo "... bo_oned"
	@echo "... bo_cont"
	@echo "... branin_system_calls"
	@echo "... bo_branin"
	@echo "... bo_display"
	@echo "... bo_disc"
	@echo "... bo_branin_display"
	@echo "... bo_branin_mcmc"
	@echo "... branin_xml"
	@echo "... bo_branin_timed"
	@echo "... bo_compare"
	@echo "... bo_hartmann"
	@echo "... matplotpp"
	@echo "... bo_camelback"
	@echo "... DesignEasy"
	@echo "... de_interface"
	@echo "... src/benchmark.o"
	@echo "... src/benchmark.i"
	@echo "... src/benchmark.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

