all:
#	gcc multi-thread.c -o mt -lpthread
	gcc ./m/mserver_wl.c -o ./m/m
	gcc ./1/1server_wl.c -o ./1/s -lpthread
	gcc ./2/2server_wl.c -o ./2/s -lpthread
	gcc ./3/3server_wl.c -o ./3/s -lpthread
	gcc ./4/4server_wl.c -o ./4/s -lpthread
	gcc ./a/aclient_wl.c -o ./a/c
	gcc ./b/bclient_wl.c -o ./b/c