PROG = white_noise

CC = g++
FLAGS = -Wall -DSC_INCLUDE_FX -O3  -lm
SC     = /usr/local/systemc-2.2.0
SC_OBJ = /home/tim/SystemC/systemc-2.2.0/objdir/src/sysc
AMS   = /home/tim/SystemC/systemc-ams-1.0Beta2
AMS_OBJ = /home/tim/SystemC/systemc-ams-1.0Beta2/src/scams/impl
INCL	= -I$(AMS)/include -I$(SC)/include
OBJS	= $(AMS_OBJ)/*/*.o $(AMS_OBJ)/*/*/*.o $(AMS_OBJ)/*/*/*/*.o $(SC_OBJ)/*/*.o $(SC_OBJ)/*/*/*.o

all: $(PROG)

Gnoise.o: Gnoise.cpp
	$(CC)  -c $(FLAGS) $(INCL) Gnoise.cpp

$(PROG): test_wn.cpp Gnoise.o
	$(CC)  $(FLAGS) $(INCL) $(OBJS) Gnoise.o test_wn.cpp -o $(PROG)
